from app.api.routes import (
    ai_cfo,
    alerts,
    auth,
    business,
    dashboard,
    expenses,
    forecast,
    gst,
    invoices,
    loan_readiness,
    loans,
    recommendations,
    reports,
    risk,
    transactions,
)

ROUTERS = [
    auth.router,
    business.router,
    dashboard.router,
    transactions.router,
    invoices.router,
    expenses.router,
    gst.router,
    loans.router,
    forecast.router,
    risk.router,
    loan_readiness.router,
    recommendations.router,
    alerts.router,
    ai_cfo.router,
    reports.router,
]
