import { useEffect, useRef, useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { Lightbulb, TrendingUp, X, Sparkles, Trash2 } from 'lucide-react';
import { Card, PageHeader, Pill, ErrorState } from '@/components/ui';
import { useToast } from '@/components/Toast';
import { getErrorMessage } from '@/lib/axios';
import recommendationService from '@/services/recommendationService';
import type { RecommendationRow } from '@/lib/mappers';

const PRIORITY_ORDER: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };

export default function Recommendations() {
  const qc = useQueryClient();
  const { addToast } = useToast();
  const { data: recs, isLoading, error, refetch } = useQuery({
    queryKey: ['recommendations'],
    queryFn: () => recommendationService.getRecommendations(),
  });

  const [priorityFilter, setPriorityFilter] = useState<'all' | string>('all');
  const [agentFilter, setAgentFilter] = useState<'all' | string>('all');
  const generatedOnce = useRef(false);

  const generateMutation = useMutation({
    mutationFn: () => recommendationService.generate(),
    onSuccess: (generated) => {
      const known = new Set((qc.getQueryData<RecommendationRow[]>(['recommendations']) || []).map((r) => r.id));
      const fresh = generated.filter((r) => !known.has(r.id)).length;

      // Show the freshly generated payload immediately, then reconcile with the server.
      if (generated.length > 0) qc.setQueryData(['recommendations'], generated);
      qc.invalidateQueries({ queryKey: ['recommendations'] });
      qc.invalidateQueries({ queryKey: ['dashboard-recommendations'] });
      qc.invalidateQueries({ queryKey: ['history'] });

      // Reveal whatever was just generated instead of hiding it behind stale filters.
      setPriorityFilter('all');
      setAgentFilter('all');

      if (fresh > 0) addToast(`Generated ${fresh} new recommendation${fresh > 1 ? 's' : ''}`, 'success');
      else if (generated.length > 0) addToast(`Refreshed ${generated.length} recommendations — no new items found`, 'info');
      else addToast('No recommendations could be generated yet. Add financial data first.', 'info');
    },
    onError: (e) => addToast(getErrorMessage(e), 'error'),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: string) => recommendationService.remove(id),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['recommendations'] });
      qc.invalidateQueries({ queryKey: ['dashboard-recommendations'] });
      addToast('Recommendation deleted', 'success');
    },
    onError: (e) => addToast(getErrorMessage(e), 'error'),
  });

  const actionMutation = useMutation({
    mutationFn: ({ id, action }: { id: string; action: 'acknowledge' | 'complete' | 'dismiss' }) => recommendationService[action](id),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['recommendations'] });
      addToast('Updated', 'success');
    },
    onError: (e) => addToast(getErrorMessage(e), 'error'),
  });

  // Auto-generate once when the list is empty.
  useEffect(() => {
    if (!isLoading && !error && (!recs || recs.length === 0) && !generatedOnce.current && !generateMutation.isPending) {
      generatedOnce.current = true;
      generateMutation.mutate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isLoading, error, recs]);

  const all = recs || [];
  const agents = ['all', ...new Set(all.map((r) => r.sourceAgent))];

  const filtered = all
    .filter((r) => r.status !== 'dismissed')
    .filter((r) => priorityFilter === 'all' || r.priority === priorityFilter)
    .filter((r) => agentFilter === 'all' || r.sourceAgent === agentFilter)
    .sort((a, b) => PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority]);

  return (
    <div className="space-y-6">
      <PageHeader
        title="Recommendations"
        subtitle="Actionable insights generated by AI agents"
        actions={
          <button
            onClick={() => generateMutation.mutate()}
            disabled={generateMutation.isPending}
            className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 disabled:bg-slate-300 text-white rounded-lg text-sm font-medium transition shadow-sm"
          >
            <Sparkles className="w-4 h-4" /> {generateMutation.isPending ? 'Generating…' : 'Generate'}
          </button>
        }
      />

      {error ? (
        <Card>
          <ErrorState message={getErrorMessage(error)} onRetry={() => refetch()} />
        </Card>
      ) : (
        <>
          {/* Filters */}
          <div className="flex flex-wrap gap-3 items-center">
            <div className="flex gap-2 flex-wrap">
              {['all', 'critical', 'high', 'medium', 'low'].map((p) => (
                <button
                  key={p}
                  onClick={() => setPriorityFilter(p)}
                  className={`px-3 py-2 rounded-lg text-sm font-medium capitalize transition ${priorityFilter === p ? 'bg-slate-900 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'}`}
                >
                  {p}
                </button>
              ))}
            </div>
            <select value={agentFilter} onChange={(e) => setAgentFilter(e.target.value)} className="px-3 py-2 border border-slate-200 rounded-lg text-sm outline-none focus:border-blue-400">
              {agents.map((a) => (
                <option key={a} value={a}>
                  {a === 'all' ? 'All agents' : a}
                </option>
              ))}
            </select>
          </div>

          {filtered.length === 0 && !isLoading ? (
            <Card className="p-12 text-center">
              <Lightbulb className="w-10 h-10 text-slate-300 mx-auto mb-3" />
              <p className="text-slate-500">No recommendations yet. Click “Generate” to analyze your business.</p>
            </Card>
          ) : (
            <div className="space-y-4">
              {filtered.map((rec, idx) => (
                <Card key={rec.id} className="p-5 hover" delay={idx * 40}>
                  <div className="flex flex-col sm:flex-row sm:items-start gap-4">
                    <div className="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center shrink-0">
                      <Lightbulb className="w-5 h-5 text-blue-600" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex flex-wrap items-center gap-2 mb-1">
                        <h3 className="text-base font-semibold text-slate-900">{rec.title}</h3>
                        <Pill value={rec.priority} />
                        <Pill value={rec.status} />
                      </div>
                      <p className="text-sm text-slate-600 mb-2">{rec.description}</p>
                      <div className="flex flex-wrap gap-x-6 gap-y-1 text-xs mb-3">
                        <span className="text-slate-400">
                          Agent: <span className="font-medium text-blue-600">{rec.sourceAgent}</span>
                        </span>
                        {rec.impact && (
                          <span className="text-slate-400">
                            Impact: <span className="font-medium text-green-600">{rec.impact}</span>
                          </span>
                        )}
                        {rec.date && <span className="text-slate-400">Date: {rec.date}</span>}
                      </div>
                      <div className="p-3 rounded-lg bg-slate-50 flex items-start gap-2">
                        <TrendingUp className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
                        <p className="text-sm text-slate-600">
                          <span className="font-medium">Action:</span> {rec.action}
                        </p>
                      </div>
                    </div>
                    <div className="flex sm:flex-col gap-2 shrink-0">
                      {rec.status === 'new' && (
                        <button
                          onClick={() => actionMutation.mutate({ id: rec.id, action: 'acknowledge' })}
                          className="px-3 py-1.5 text-xs font-medium text-slate-600 border border-slate-200 hover:bg-slate-50 rounded-lg transition"
                        >
                          Acknowledge
                        </button>
                      )}
                      {rec.status !== 'completed' && (
                        <button
                          onClick={() => actionMutation.mutate({ id: rec.id, action: 'complete' })}
                          className="px-3 py-1.5 text-xs font-medium text-green-600 border border-green-200 hover:bg-green-50 rounded-lg transition"
                        >
                          Done
                        </button>
                      )}
                      <button
                        onClick={() => actionMutation.mutate({ id: rec.id, action: 'dismiss' })}
                        className="p-2 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition"
                        aria-label="Dismiss"
                        title="Dismiss"
                      >
                        <X className="w-4 h-4" />
                      </button>
                      <button
                        onClick={() => {
                          if (window.confirm('Delete this recommendation permanently?')) deleteMutation.mutate(rec.id);
                        }}
                        className="p-2 rounded-lg hover:bg-red-50 text-slate-400 hover:text-red-600 transition"
                        aria-label="Delete"
                        title="Delete"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>
                </Card>
              ))}
            </div>
          )}
        </>
      )}
    </div>
  );
}
