import { useState } from 'react';
import { Lightbulb, TrendingUp, X } from 'lucide-react';
import { Card, PageHeader, Pill } from '@/components/ui';
import { mockRecommendations } from '@/mock';

const PRIORITY_ORDER: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };

export default function Recommendations() {
  const [priorityFilter, setPriorityFilter] = useState<'all' | string>('all');
  const [agentFilter, setAgentFilter] = useState<'all' | string>('all');
  const [dismissed, setDismissed] = useState<Set<string>>(new Set());

  const agents = ['all', ...new Set(mockRecommendations.map((r) => r.sourceAgent))];

  const filtered = mockRecommendations
    .filter((r) => !dismissed.has(r.id))
    .filter((r) => priorityFilter === 'all' || r.priority === priorityFilter)
    .filter((r) => agentFilter === 'all' || r.sourceAgent === agentFilter)
    .sort((a, b) => PRIORITY_ORDER[a.priority] - PRIORITY_ORDER[b.priority]);

  const dismiss = (id: string) => setDismissed((prev) => new Set(prev).add(id));

  return (
    <div className="space-y-6">
      <PageHeader
        title="Recommendations"
        subtitle="Actionable insights generated by AI agents"
      />

      {/* Filters */}
      <div className="flex flex-wrap gap-3 items-center">
        <div className="flex gap-2 flex-wrap">
          {['all', 'critical', 'high', 'medium', 'low'].map((p) => (
            <button
              key={p}
              onClick={() => setPriorityFilter(p)}
              className={`px-3 py-2 rounded-lg text-sm font-medium capitalize transition ${priorityFilter === p ? 'bg-slate-900 text-white' : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'}`}
            >
              {p}
            </button>
          ))}
        </div>
        <select
          value={agentFilter}
          onChange={(e) => setAgentFilter(e.target.value)}
          className="px-3 py-2 border border-slate-200 rounded-lg text-sm outline-none focus:border-blue-400"
        >
          {agents.map((a) => <option key={a} value={a}>{a === 'all' ? 'All agents' : a}</option>)}
        </select>
      </div>

      {filtered.length === 0 ? (
        <Card className="p-12 text-center">
          <Lightbulb className="w-10 h-10 text-slate-300 mx-auto mb-3" />
          <p className="text-slate-500">No recommendations match your filters.</p>
        </Card>
      ) : (
        <div className="space-y-4">
          {filtered.map((rec, idx) => (
            <Card key={rec.id} className="p-5 hover" delay={idx * 40}>
              <div className="flex flex-col sm:flex-row sm:items-start gap-4">
                <div className="w-10 h-10 rounded-lg bg-blue-50 flex items-center justify-center shrink-0">
                  <Lightbulb className="w-5 h-5 text-blue-600" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-2 mb-1">
                    <h3 className="text-base font-semibold text-slate-900">{rec.title}</h3>
                    <Pill value={rec.priority} />
                    <Pill value={rec.status} />
                  </div>
                  <p className="text-sm text-slate-600 mb-2">{rec.description}</p>
                  <div className="flex flex-wrap gap-x-6 gap-y-1 text-xs mb-3">
                    <span className="text-slate-400">Agent: <span className="font-medium text-blue-600">{rec.sourceAgent}</span></span>
                    <span className="text-slate-400">Impact: <span className="font-medium text-green-600">{rec.impact}</span></span>
                    <span className="text-slate-400">Date: {rec.date}</span>
                  </div>
                  <div className="p-3 rounded-lg bg-slate-50 flex items-start gap-2">
                    <TrendingUp className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
                    <p className="text-sm text-slate-600"><span className="font-medium">Action:</span> {rec.description}</p>
                  </div>
                </div>
                <button onClick={() => dismiss(rec.id)} className="shrink-0 p-2 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-600 transition" aria-label="Dismiss">
                  <X className="w-4 h-4" />
                </button>
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
